# Generated by Django 6.0.5 on 2026-05-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('rank', models.IntegerField(db_column='Rank')),
                ('pos', models.CharField(db_column='Pos', max_length=50)),
                ('player', models.CharField(db_column='Player', max_length=50)),
                ('tm', models.CharField(blank=True, db_column='Tm', max_length=50, null=True)),
                ('g', models.IntegerField(blank=True, db_column='G', null=True)),
                ('gs', models.IntegerField(blank=True, db_column='GS', null=True)),
                ('cmp', models.IntegerField(blank=True, db_column='Cmp', null=True)),
                ('att', models.IntegerField(blank=True, db_column='Att', null=True)),
                ('yds', models.IntegerField(blank=True, db_column='Yds', null=True)),
                ('td', models.IntegerField(blank=True, db_column='TD', null=True)),
                ('passing_int', models.IntegerField(blank=True, db_column='Int', null=True)),
                ('att2', models.IntegerField(blank=True, db_column='Att2', null=True)),
                ('yds2', models.IntegerField(blank=True, db_column='Yds2', null=True)),
                ('td2', models.IntegerField(blank=True, db_column='TD2', null=True)),
                ('rec', models.IntegerField(blank=True, db_column='Rec', null=True)),
                ('yds3', models.IntegerField(blank=True, db_column='Yds3', null=True)),
                ('td3', models.IntegerField(blank=True, db_column='TD3', null=True)),
                ('solo', models.IntegerField(blank=True, db_column='Solo', null=True)),
                ('sk', models.FloatField(blank=True, db_column='Sk', null=True)),
                ('int2', models.IntegerField(blank=True, db_column='Int2', null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
