# Generated by Django 6.0.4 on 2026-04-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='User',
        ),
    ]
