# Generated by Django 6.0.5 on 2026-05-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': True},
        ),
    ]
